c
c	cmstrt
C** 
C**    @(#)CMSTRT.INC	1.1    3/10/88
C**
C**
C***********************************************************************
C**
C**                 PLOT+ Scientific Graphics System
C**
C***********************************************************************
C**
C**
c
	COMMON/CMSTRT/SRTFIL
	CHARACTER SRTFIL*81
c
c	srtfil	command file specified on initial VMS line
c
c*******************************************************************
