c
c	cpftn5
C** 
C**    @(#)CPFTN5.INC	1.1    3/10/88
C**
C**
C***********************************************************************
C**
C**                 PLOT+ Scientific Graphics System
C**
C***********************************************************************
C**
C**
c
	COMMON/CPFTN5/PRMPT
	CHARACTER PRMPT*40
c
c	prmpt	prompt for COMRD5 input from a terminal
c
c*******************************************************************
