#! /bin/csh -f
# *sh* 9/00

# like clean but eliminates all diagnostic outputs

# usage:
    # ultra_clean log_file_name

# produces output file name "clean_ultra_{log_file_name}"

sed -e s/\(G...\)/\(G999\)/g -e s/\(AX...\)/\(AX999\)/g < $argv[1] | egrep -v '^ alloc|^ deallo|^ \-DELE|^ getgrid|^ found|^ eval|^PPL plot|^ reading|^ regrid|^ nulgrd|^ nulrgd|^ rdstride|^ pseudo|^ constan cnst|^ const_v|^ pseudo|^ string str|^		:history = "FERRET|^ pass #2|SESSION_DATE|SESSION_TIME' >! clean_ultra_$argv[1]
